import type { GrammarTopic } from '../../types';

/** Modul 4 — Fe'l: tuslanish, zamonlar, aspekt, refleksiv, buyruq (A1-A2) */
export const MODULE_4: GrammarTopic[] = [
  {
    id: 'm4-conjugation',
    module: 4,
    order: 1,
    level: 'A1',
    title: 'I va II tuslanish',
    subtitle: 'читать → читаю, говорить → говорю',
    theory: [
      {
        heading: 'I tuslanish (е-tipi)',
        body: "Ko'pchilik -ать/-ять fe'llari: читать, работать, знать, делать, понимать, гулять.",
        table: [
          ['Shaxs', 'чита́ть', 'рабо́тать'],
          ['я', 'чита́ю', 'рабо́таю'],
          ['ты', 'чита́ешь', 'рабо́таешь'],
          ['он/она́', 'чита́ет', 'рабо́тает'],
          ['мы', 'чита́ем', 'рабо́таем'],
          ['вы', 'чита́ете', 'рабо́таете'],
          ['они́', 'чита́ют', 'рабо́тают'],
        ],
      },
      {
        heading: 'II tuslanish (и-tipi)',
        body: "Ko'pchilik -ить fe'llari: говорить, любить, учить, смотреть (istisno -еть), слышать.",
        table: [
          ['Shaxs', 'говори́ть', 'люби́ть'],
          ['я', 'говорю́', 'люблю́'],
          ['ты', 'говори́шь', 'лю́бишь'],
          ['он/она́', 'говори́т', 'лю́бит'],
          ['мы', 'говори́м', 'лю́бим'],
          ['вы', 'говори́те', 'лю́бите'],
          ['они́', 'говоря́т', 'лю́бят'],
        ],
      },
      {
        heading: 'Qanday farqlash',
        body: "Asosiy mo'ljal: -ить → II tuslanish (говорить), qolganlari → I tuslanish (читать). Istisnolarni yodlang: смотреть, видеть, слышать, ненавидеть — II; брить, стелить — I. любить da л qo'shiladi: люблю.",
      },
    ],
    comparisonWithUzbek:
      "O'zbek tilida ham fe'l shaxsga qarab o'zgaradi (o'qiyMAN, o'qiySAN, o'qiyDI) — shuning uchun bu tizim sizga tanish. Faqat qo'shimchalar boshqa va ikkita tip bor.",
    examples: [
      { ru: 'Я чита́ю кни́гу.', uz: 'Men kitob o‘qiyapman.' },
      { ru: 'Ты говори́шь по-ру́сски?', uz: 'Sen ruscha gapirasanmi?' },
      { ru: 'Он рабо́тает в ба́нке.', uz: 'U bankda ishlaydi.' },
      { ru: 'Мы лю́бим спорт.', uz: 'Biz sportni yaxshi ko‘ramiz.' },
      { ru: 'Они́ живу́т в Москве́.', uz: 'Ular Moskvada yashashadi.', note: 'жить: живу, живёшь...' },
    ],
    commonMistakes: [
      { wrong: 'я читать', right: 'я читаю', why_uz: "Infinitiv shaxsga moslanishi shart: я читаю." },
      { wrong: 'он говорят', right: 'он говорит', why_uz: "он → -ит, они → -ят." },
      { wrong: 'я любю', right: 'я люблю', why_uz: "любить — я shaklida л orttiriladi: люблю." },
      { wrong: 'ты читает', right: 'ты читаешь', why_uz: 'ты doim -шь bilan: читаешь, говоришь.' },
    ],
    exercises: [
      { id: 'm4-conj-1', type: 'conjugationDrill', prompt: 'читать → я ...', answer: 'читаю', explanation_uz: 'I tuslanish: -ю.' },
      { id: 'm4-conj-2', type: 'conjugationDrill', prompt: 'читать → ты ...', answer: 'читаешь', explanation_uz: '-ешь.' },
      { id: 'm4-conj-3', type: 'conjugationDrill', prompt: 'говорить → он ...', answer: 'говорит', explanation_uz: 'II tuslanish: -ит.' },
      { id: 'm4-conj-4', type: 'conjugationDrill', prompt: 'работать → мы ...', answer: 'работаем', explanation_uz: '-ем.' },
      { id: 'm4-conj-5', type: 'conjugationDrill', prompt: 'любить → я ...', answer: 'люблю', explanation_uz: "л orttiriladi: люблю." },
      { id: 'm4-conj-6', type: 'conjugationDrill', prompt: 'говорить → они ...', answer: 'говорят', explanation_uz: 'II tuslanish они → -ят.' },
      { id: 'm4-conj-7', type: 'choose', prompt: 'Qaysi fe’l II tuslanishga kiradi?', answer: 'смотреть', choices: ['смотреть', 'читать', 'знать', 'гулять'], explanation_uz: 'смотреть — istisno, II tuslanish: смотрю, смотришь.' },
      { id: 'm4-conj-8', type: 'errorHunt', prompt: 'Xatoni toping: «Ты говорит по-русски?»', answer: 'Ты говоришь по-русски?', explanation_uz: 'ты → говоришь.' },
      { id: 'm4-conj-9', type: 'conjugationDrill', prompt: 'жить → я ...', answer: 'живу', explanation_uz: 'жить: живу, живёшь, живёт...' },
      { id: 'm4-conj-10', type: 'translate', prompt: 'Tarjima qiling: «Biz Toshkentda yashaymiz»', answer: 'Мы живём в Ташкенте', explanation_uz: 'мы живём.' },
    ],
  },
  {
    id: 'm4-irregular',
    module: 4,
    order: 2,
    level: 'A1',
    title: "Eng muhim noto'g'ri fe'llar",
    subtitle: 'хотеть, мочь, есть, пить, идти',
    theory: [
      {
        heading: 'хотеть (xohlamoq) — aralash tip',
        body: "Birlikda I tipdek, ko'plikda II tipdek tuslanadi.",
        table: [
          ['я хочу́', 'мы хоти́м'],
          ['ты хо́чешь', 'вы хоти́те'],
          ['он хо́чет', 'они́ хотя́т'],
        ],
      },
      {
        heading: 'мочь (qila olmoq)',
        body: "г/ж almashinadi: я могу́, ты мо́жешь, он мо́жет, мы мо́жем, вы мо́жете, они́ мо́гут.",
      },
      {
        heading: 'есть (yemoq) va пить (ichmoq)',
        body: "есть: ем, ешь, ест, еди́м, еди́те, едя́т. пить: пью, пьёшь, пьёт, пьём, пьёте, пьют.",
      },
      {
        heading: 'идти (bormoq) va ехать (transportda bormoq)',
        body: "идти: иду́, идёшь, идёт, идём, идёте, иду́т. ехать: е́ду, е́дешь, е́дет, е́дем, е́дете, е́дут.",
      },
    ],
    comparisonWithUzbek:
      "Bu fe'llar eng ko'p ishlatiladiganlar — ularni alohida-alohida, qo'shiq kabi yodlab olish kerak: хочу-хочешь-хочет... O'zbek tilidagi 'yemoq/ichmoq' kabi kundalik fe'llar.",
    examples: [
      { ru: 'Я хочу́ чай.', uz: 'Men choy xohlayman.' },
      { ru: 'Ты мо́жешь помо́чь?', uz: 'Yordam bera olasanmi?' },
      { ru: 'Что ты ешь?', uz: 'Nima yeyapsan?' },
      { ru: 'Я пью ко́фе ка́ждое у́тро.', uz: 'Har kuni ertalab kofe ichaman.' },
      { ru: 'Куда́ ты идёшь?', uz: 'Qayerga ketyapsan?' },
    ],
    commonMistakes: [
      { wrong: 'я хотю', right: 'я хочу', why_uz: 'хотеть → хочу (т→ч).' },
      { wrong: 'он можут', right: 'он может', why_uz: 'он → может, они → могут.' },
      { wrong: 'я ем (пить ma’nosida)', right: 'я пью', why_uz: 'есть — yemoq, пить — ichmoq.' },
      { wrong: 'я идю', right: 'я иду', why_uz: 'идти → иду.' },
    ],
    exercises: [
      { id: 'm4-irr-1', type: 'conjugationDrill', prompt: 'хотеть → я ...', answer: 'хочу', explanation_uz: 'я хочу.' },
      { id: 'm4-irr-2', type: 'conjugationDrill', prompt: 'хотеть → они ...', answer: 'хотят', explanation_uz: "Ko'plikda II tip: хотят." },
      { id: 'm4-irr-3', type: 'conjugationDrill', prompt: 'мочь → ты ...', answer: 'можешь', explanation_uz: 'г→ж: можешь.' },
      { id: 'm4-irr-4', type: 'conjugationDrill', prompt: 'есть → я ...', answer: 'ем', explanation_uz: 'я ем.' },
      { id: 'm4-irr-5', type: 'conjugationDrill', prompt: 'пить → ты ...', answer: 'пьёшь', explanation_uz: 'пьёшь — ь bilan.' },
      { id: 'm4-irr-6', type: 'conjugationDrill', prompt: 'идти → мы ...', answer: 'идём', explanation_uz: 'мы идём.' },
      { id: 'm4-irr-7', type: 'translate', prompt: 'Tarjima qiling: «Men suv ichmoqchiman» (хотеть, пить, вода)', answer: 'Я хочу пить воду', explanation_uz: 'хотеть + infinitiv.' },
      { id: 'm4-irr-8', type: 'errorHunt', prompt: 'Xatoni toping: «Они может прийти»', answer: 'Они могут прийти', explanation_uz: 'они → могут.' },
      { id: 'm4-irr-9', type: 'conjugationDrill', prompt: 'ехать → он ...', answer: 'едет', explanation_uz: 'он едет.' },
      { id: 'm4-irr-10', type: 'choose', prompt: '«Nima yeyapsan?» ruscha qanday?', answer: 'Что ты ешь?', choices: ['Что ты ешь?', 'Что ты есть?', 'Что ты едишь?', 'Что ты пьёшь?'], explanation_uz: 'ты ешь.' },
    ],
  },
  {
    id: 'm4-past',
    module: 4,
    order: 3,
    level: 'A1',
    title: "O'tgan zamon",
    subtitle: 'читал, читала, читало, читали',
    theory: [
      {
        heading: 'Yasalishi',
        body: "Infinitivdan -ть olib tashlanib -л qo'shiladi. O'tgan zamon shaxsga emas, RODGA moslashadi!",
        table: [
          ['Kim', "Qo'shimcha", 'Misol'],
          ['он (м)', '-л', 'он чита́л'],
          ['она́ (ж)', '-ла', 'она́ чита́ла'],
          ['оно́ (с)', '-ло', 'оно́ бы́ло'],
          ["ko'plik", '-ли', 'они́ чита́ли'],
        ],
      },
      {
        heading: 'Muhim jihatlar',
        body: "я/ты uchun ham rod muhim: я читал (erkak), я читала (ayol). Istisnolar: идти → шёл/шла/шли, мочь → мог/могла́/могли́, есть → ел/е́ла/е́ли.",
      },
    ],
    comparisonWithUzbek:
      "O'zbek tilida o'tgan zamon shaxsga moslashadi (o'qiDIM, o'qiDING), rus tilida esa rodga (читал/читала). Ayol kishi o'zi haqida doim -ла bilan gapiradi: Я была дома.",
    examples: [
      { ru: 'Вчера́ я чита́л кни́гу.', uz: 'Kecha kitob o‘qidim. (erkak)' },
      { ru: 'Она́ рабо́тала в шко́ле.', uz: 'U maktabda ishlagan.' },
      { ru: 'Мы смотре́ли фильм.', uz: 'Biz film ko‘rdik.' },
      { ru: 'Он шёл домо́й.', uz: 'U uyga ketayotgan edi.', note: 'идти → шёл' },
      { ru: 'Я была́ в Москве́.', uz: 'Men Moskvada bo‘lganman. (ayol)' },
    ],
    commonMistakes: [
      { wrong: 'Она читал', right: 'Она читала', why_uz: 'Ayol rod → -ла.' },
      { wrong: 'Они читала', right: 'Они читали', why_uz: "Ko'plik → -ли." },
      { wrong: 'Он идал', right: 'Он шёл', why_uz: "идти ning o'tgan zamoni butunlay boshqa: шёл/шла/шли." },
    ],
    exercises: [
      { id: 'm4-past-1', type: 'transform', prompt: "O'tgan zamonga o'tkazing: «Он читает»", answer: 'Он читал', explanation_uz: 'м → -л.' },
      { id: 'm4-past-2', type: 'transform', prompt: "O'tgan zamonga o'tkazing: «Она работает»", answer: 'Она работала', explanation_uz: 'ж → -ла.' },
      { id: 'm4-past-3', type: 'transform', prompt: "O'tgan zamonga o'tkazing: «Мы смотрим фильм»", answer: 'Мы смотрели фильм', explanation_uz: "ko'plik → -ли." },
      { id: 'm4-past-4', type: 'fillBlank', prompt: 'Вчера я (ayol) ___ дома. (быть)', answer: 'была', explanation_uz: 'ж → была.' },
      { id: 'm4-past-5', type: 'choose', prompt: "идти fe'lining o'tgan zamoni (м)?", answer: 'шёл', choices: ['шёл', 'идал', 'идёл', 'ходил'], explanation_uz: 'идти → шёл (istisno).' },
      { id: 'm4-past-6', type: 'errorHunt', prompt: 'Xatoni toping: «Мама вчера читал книгу»', answer: 'Мама вчера читала книгу', explanation_uz: 'мама ж → читала.' },
      { id: 'm4-past-7', type: 'conjugationDrill', prompt: 'мочь → она ... (o‘tgan zamon)', answer: 'могла', explanation_uz: 'мог/могла/могли.' },
      { id: 'm4-past-8', type: 'translate', prompt: 'Tarjima qiling: «Biz kecha ishladik»', answer: 'Мы вчера работали', explanation_uz: 'работали.' },
    ],
  },
  {
    id: 'm4-future',
    module: 4,
    order: 4,
    level: 'A2',
    title: 'Kelasi zamon',
    subtitle: 'буду читать / прочитаю',
    theory: [
      {
        heading: 'Ikki xil kelasi zamon',
        body: "1) Murakkab (НСВ): быть + infinitiv — davomli/takroriy ish: Я буду читать (o'qib o'tiraman). 2) Sodda (СВ): sovershenniy fe'lning hozirgi zamon shakli — bitta tugallangan ish: Я прочитаю (o'qib bo'laman).",
        table: [
          ['Shaxs', 'быть', 'Misol'],
          ['я', 'бу́ду', 'бу́ду чита́ть'],
          ['ты', 'бу́дешь', 'бу́дешь чита́ть'],
          ['он', 'бу́дет', 'бу́дет чита́ть'],
          ['мы', 'бу́дем', 'бу́дем чита́ть'],
          ['вы', 'бу́дете', 'бу́дете чита́ть'],
          ['они́', 'бу́дут', 'бу́дут чита́ть'],
        ],
      },
      {
        heading: 'Diqqat',
        body: "СВ fe'l (прочитать, сделать, купить) hozirgi zamon shaklida kelajakni bildiradi: Я прочитаю завтра — ertaga o'qib bo'laman. СВ bilan буду ishlatib BO'LMAYDI: «буду прочитать» — xato!",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha 'o'qiyman (ertaga)' ikkala ruscha shaklga ham to'g'ri keladi. Farq nima muhimligida: jarayon bo'lsa буду читать, natija bo'lsa прочитаю.",
    examples: [
      { ru: 'За́втра я бу́ду рабо́тать.', uz: 'Ertaga ishlayman (kun davomida).' },
      { ru: 'Я прочита́ю э́ту кни́гу за́втра.', uz: 'Bu kitobni ertaga o‘qib bo‘laman.' },
      { ru: 'Мы бу́дем смотре́ть фильм ве́чером.', uz: 'Kechqurun film ko‘ramiz.' },
      { ru: 'Он ку́пит хлеб по́сле рабо́ты.', uz: 'U ishdan keyin non sotib oladi.', note: 'СВ — sodda kelasi' },
    ],
    commonMistakes: [
      { wrong: 'буду прочитать', right: 'прочитаю YOKI буду читать', why_uz: 'буду faqat НСВ infinitiv bilan keladi.' },
      { wrong: 'я будет', right: 'я буду', why_uz: 'быть tuslanadi: я буду, он будет.' },
    ],
    exercises: [
      { id: 'm4-fut-1', type: 'fillBlank', prompt: 'Завтра мы ___ отдыхать. (быть)', answer: 'будем', explanation_uz: 'мы будем.' },
      { id: 'm4-fut-2', type: 'choose', prompt: "Qaysi gap to'g'ri?", answer: 'Я буду читать вечером', choices: ['Я буду читать вечером', 'Я буду прочитать вечером', 'Я буду читаю вечером', 'Я читаю буду вечером'], explanation_uz: 'буду + НСВ infinitiv.' },
      { id: 'm4-fut-3', type: 'transform', prompt: "Kelasi zamonga o'tkazing: «Он работает»", answer: 'Он будет работать', explanation_uz: 'будет + infinitiv.' },
      { id: 'm4-fut-4', type: 'choose', prompt: '«Ertaga sotib olaman (bitta ish, natija)» — qaysi shakl?', answer: 'куплю', choices: ['куплю', 'буду купить', 'покупаю', 'буду куплю'], explanation_uz: 'СВ sodda kelasi: куплю.' },
      { id: 'm4-fut-5', type: 'fillBlank', prompt: 'Ты ___ дома вечером? (быть)', answer: 'будешь', explanation_uz: 'ты будешь.' },
      { id: 'm4-fut-6', type: 'errorHunt', prompt: 'Xatoni toping: «Завтра я буду сделать домашнее задание»', answer: 'Завтра я сделаю домашнее задание', explanation_uz: 'сделать — СВ, буду bilan kelmaydi.' },
      { id: 'm4-fut-7', type: 'translate', prompt: 'Tarjima qiling: «Kechqurun televizor ko‘raman (jarayon)»', answer: 'Вечером я буду смотреть телевизор', explanation_uz: 'Davomli ish — буду смотреть.' },
    ],
  },
  {
    id: 'm4-aspect-intro',
    module: 4,
    order: 5,
    level: 'A2',
    title: "Fe'l aspekti I: НСВ va СВ nima?",
    subtitle: 'читать — прочитать',
    theory: [
      {
        heading: 'Ikki aspekt',
        body: "Deyarli har bir ruscha fe'l juft bo'lib yashaydi: НСВ (несовершенный вид) — jarayon, takror, davomiylik; СВ (совершенный вид) — bitta tugallangan natija. читать (o'qish jarayoni) — прочитать (o'qib bo'lish).",
        table: [
          ['НСВ (jarayon)', 'СВ (natija)', "Ma'no"],
          ['чита́ть', 'прочита́ть', "o'qimoq"],
          ['де́лать', 'сде́лать', 'qilmoq'],
          ['писа́ть', 'написа́ть', 'yozmoq'],
          ['покупа́ть', 'купи́ть', 'sotib olmoq'],
          ['говори́ть', 'сказа́ть', 'gapirmoq/aytmoq'],
          ['смотре́ть', 'посмотре́ть', "ko'rmoq"],
        ],
      },
      {
        heading: 'Zamonlar bilan',
        body: "НСВ uchchala zamonda ham bor: читал — читаю — буду читать. СВ da hozirgi zamon YO'Q (natija hozir bo'lishi mumkin emas): прочитал — [—] — прочитаю.",
      },
    ],
    comparisonWithUzbek:
      "O'zbekchada bunga yaqin narsa: 'o'qiyotgan edim' (jarayon, НСВ) va 'o'qib bo'ldim / o'qib chiqdim' (natija, СВ). Ruscha СВ ko'pincha o'zbekcha '-b bo'lmoq', '-b chiqmoq', '-b qo'ymoq' ko'makchi fe'llariga mos keladi.",
    examples: [
      { ru: 'Вчера́ я чита́л весь день.', uz: 'Kecha kun bo‘yi o‘qidim (jarayon).', note: 'НСВ' },
      { ru: 'Вчера́ я прочита́л э́ту кни́гу.', uz: 'Kecha bu kitobni o‘qib bo‘ldim.', note: 'СВ — natija' },
      { ru: 'Я ка́ждый день де́лаю заря́дку.', uz: 'Har kuni badantarbiya qilaman.', note: 'takror → НСВ' },
      { ru: 'Я сде́лал дома́шнее зада́ние.', uz: 'Uy vazifasini qilib bo‘ldim.', note: 'СВ' },
    ],
    commonMistakes: [
      { wrong: 'Я прочитаю каждый день', right: 'Я читаю каждый день', why_uz: 'Takroriy ish faqat НСВ bilan.' },
      { wrong: 'Я сейчас прочитаю книгу (hozir o‘qiyapman ma’nosida)', right: 'Я сейчас читаю книгу', why_uz: "СВ da hozirgi zamon yo'q — hozir bo'layotgan ish НСВ." },
    ],
    exercises: [
      { id: 'm4-asp1-1', type: 'choose', prompt: '«прочитать» qaysi aspekt?', answer: 'СВ (natija)', choices: ['СВ (natija)', 'НСВ (jarayon)'], explanation_uz: 'про- prefiksi natijani bildiradi.' },
      { id: 'm4-asp1-2', type: 'choose', prompt: '«Har kuni» bilan qaysi aspekt keladi?', answer: 'НСВ', choices: ['НСВ', 'СВ'], explanation_uz: 'Takror — doim НСВ: каждый день читаю.' },
      { id: 'm4-asp1-3', type: 'choose', prompt: 'делать fe’lining СВ jufti?', answer: 'сделать', choices: ['сделать', 'поделать', 'наделать', 'доделать'], explanation_uz: 'делать — сделать.' },
      { id: 'm4-asp1-4', type: 'choose', prompt: 'говорить fe’lining СВ jufti?', answer: 'сказать', choices: ['сказать', 'поговорить', 'разговаривать', 'заговорить'], explanation_uz: "Aytmoq ma'nosida: сказать." },
      { id: 'm4-asp1-5', type: 'choose', prompt: 'Qaysi aspektda hozirgi zamon YO‘Q?', answer: 'СВ', choices: ['СВ', 'НСВ'], explanation_uz: "Natija hozir sodir bo'la olmaydi." },
      { id: 'm4-asp1-6', type: 'fillBlank', prompt: 'Вчера я ___ это письмо за час. (написать, м)', answer: 'написал', explanation_uz: "Tugallangan natija → СВ написал." },
      { id: 'm4-asp1-7', type: 'fillBlank', prompt: 'Я часто ___ письма. (писать)', answer: 'пишу', explanation_uz: 'часто → НСВ пишу.' },
      { id: 'm4-asp1-8', type: 'choose', prompt: 'покупать fe’lining СВ jufti?', answer: 'купить', choices: ['купить', 'скупать', 'закупать', 'покупить'], explanation_uz: 'покупать — купить (juftlik boshqa ildizdan).' },
    ],
  },
  {
    id: 'm4-aspect-usage',
    module: 4,
    order: 6,
    level: 'A2',
    title: "Fe'l aspekti II: qachon qaysi birini",
    subtitle: 'Signal so‘zlar va vaziyatlar',
    theory: [
      {
        heading: 'НСВ signallari',
        body: "часто (tez-tez), всегда (doim), обычно (odatda), каждый день (har kuni), долго (uzoq), весь день (kun bo'yi), сейчас (hozir) — bularning hammasi НСВ talab qiladi.",
      },
      {
        heading: 'СВ signallari',
        body: "уже (allaqachon), наконец (nihoyat), вдруг (to'satdan), быстро + natija, за час (bir soat ichida), bitta marta tugallangan ish — СВ.",
        table: [
          ['Vaziyat', 'Aspekt', 'Misol'],
          ['Jarayon hozir', 'НСВ', 'Я сейча́с чита́ю'],
          ['Takror odat', 'НСВ', 'Я ча́сто чита́ю'],
          ['Natija bor', 'СВ', 'Я прочита́л кни́гу'],
          ['Davomiylik', 'НСВ', 'Я до́лго чита́л'],
          ["Bo'lib o'tgan fakt", 'НСВ', 'Ты чита́л «Войну и мир»?'],
        ],
      },
      {
        heading: 'Infinitiv bilan',
        body: "начать/продолжать/закончить + faqat НСВ: начал читать. хотеть/мочь — ikkalasi ham mumkin, ma'noga qarab: хочу читать (o'qib o'tirishni) / хочу прочитать (o'qib bo'lishni).",
      },
    ],
    comparisonWithUzbek:
      "Signal so'z usuli eng ishonchli yo'l: 'har kuni/odatda/hozir' ko'rsangiz НСВ, 'allaqachon/nihoyat/...-b bo'ldi' ko'rsangiz СВ deb o'ylang.",
    examples: [
      { ru: 'Я уже́ сде́лал уро́ки.', uz: 'Men darslarni allaqachon qilib bo‘ldim.', note: 'уже → СВ' },
      { ru: 'Он до́лго писа́л письмо́.', uz: 'U xatni uzoq yozdi.', note: 'долго → НСВ' },
      { ru: 'Она́ начала́ учи́ть ру́сский.', uz: 'U rus tilini o‘rgana boshladi.', note: 'начать + НСВ' },
      { ru: 'Вдруг он позвони́л.', uz: 'To‘satdan u qo‘ng‘iroq qildi.', note: 'вдруг → СВ' },
    ],
    commonMistakes: [
      { wrong: 'Я начал прочитать', right: 'Я начал читать', why_uz: 'начать dan keyin faqat НСВ.' },
      { wrong: 'Я долго прочитал', right: 'Я долго читал', why_uz: 'долго — davomiylik → НСВ.' },
      { wrong: 'Я уже делал уроки (tugatdim ma’nosida)', right: 'Я уже сделал уроки', why_uz: "Natija tayyor bo'lsa СВ." },
    ],
    exercises: [
      { id: 'm4-asp2-1', type: 'choose', prompt: 'Я обычно ___ в 7 часов. (вставать/встать)', answer: 'встаю', choices: ['встаю', 'встану', 'встал', 'вставал'], explanation_uz: 'обычно → НСВ hozirgi zamon.' },
      { id: 'm4-asp2-2', type: 'choose', prompt: 'Я уже ___ эту книгу. (читать/прочитать)', answer: 'прочитал', choices: ['прочитал', 'читал', 'читаю', 'буду читать'], explanation_uz: 'уже + natija → СВ.' },
      { id: 'm4-asp2-3', type: 'choose', prompt: 'Он начал ___ письмо. (писать/написать)', answer: 'писать', choices: ['писать', 'написать'], explanation_uz: 'начать + НСВ.' },
      { id: 'm4-asp2-4', type: 'choose', prompt: 'Мы долго ___ фильм. (смотреть/посмотреть)', answer: 'смотрели', choices: ['смотрели', 'посмотрели'], explanation_uz: 'долго → НСВ.' },
      { id: 'm4-asp2-5', type: 'choose', prompt: 'Вдруг она ___ . (звонить/позвонить)', answer: 'позвонила', choices: ['позвонила', 'звонила'], explanation_uz: "вдруг → СВ — to'satdan bitta hodisa." },
      { id: 'm4-asp2-6', type: 'fillBlank', prompt: 'Каждое утро я ___ кофе. (пить)', answer: 'пью', explanation_uz: 'Takror odat → НСВ пью.' },
      { id: 'm4-asp2-7', type: 'errorHunt', prompt: 'Xatoni toping: «Я каждый день прочитаю газету»', answer: 'Я каждый день читаю газету', explanation_uz: 'каждый день → НСВ.' },
      { id: 'm4-asp2-8', type: 'translate', prompt: 'Tarjima qiling: «Men xatni yozib bo‘ldim» (письмо)', answer: 'Я написал письмо', explanation_uz: 'Natija → СВ написал.' },
    ],
  },
  {
    id: 'm4-reflexive',
    module: 4,
    order: 7,
    level: 'A2',
    title: "Refleksiv fe'llar (-ся)",
    subtitle: 'учиться, заниматься, нравиться',
    theory: [
      {
        heading: '-ся nima',
        body: "-ся (undoshdan keyin) / -сь (unlidan keyin) qo'shimchasi fe'lga 'o'z-o'ziga' yoki holat ma'nosini beradi: учиться (o'qimoq — o'quv yurtida), мыться (yuvinmoq), встречаться (uchrashmoq).",
        table: [
          ['Shaxs', 'учи́ться', 'занима́ться'],
          ['я', 'учу́сь', 'занима́юсь'],
          ['ты', 'у́чишься', 'занима́ешься'],
          ['он', 'у́чится', 'занима́ется'],
          ['мы', 'у́чимся', 'занима́емся'],
          ['вы', 'у́читесь', 'занима́етесь'],
          ['они́', 'у́чатся', 'занима́ются'],
        ],
      },
      {
        heading: 'Eng muhim -ся fe\'llari',
        body: "учиться (где? — o'qimoq), заниматься (чем? — shug'ullanmoq), нравиться (yoqmoq), называться (atalmoq), находиться (joylashmoq), встречаться (uchrashmoq), улыбаться (jilmaymoq), бояться (qo'rqmoq).",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha '-in/-lan' nisbat qo'shimchalariga o'xshaydi: yuvmoq → yuvINmoq = мыть → мыться; tayyorlamoq → tayyorLANmoq = готовить → готовиться.",
    examples: [
      { ru: 'Я учу́сь в университе́те.', uz: 'Men universitetda o‘qiyman.' },
      { ru: 'Он занима́ется спо́ртом.', uz: 'U sport bilan shug‘ullanadi.' },
      { ru: 'Как называ́ется э́та у́лица?', uz: 'Bu ko‘cha qanday ataladi?' },
      { ru: 'Где нахо́дится вокза́л?', uz: 'Vokzal qayerda joylashgan?' },
      { ru: 'Я бою́сь соба́к.', uz: 'Men itlardan qo‘rqaman.', note: 'бояться + Р.п' },
    ],
    commonMistakes: [
      { wrong: 'Я учу в университете', right: 'Я учусь в университете', why_uz: "учить — o'rgatmoq/yodlamoq, учиться — o'qimoq (o'quv yurtida)." },
      { wrong: 'он учится-ся', right: 'он учится', why_uz: '-ся bir marta.' },
      { wrong: 'я занимаюсь спорт', right: 'я занимаюсь спортом', why_uz: 'заниматься + Т.п.' },
    ],
    exercises: [
      { id: 'm4-refl-1', type: 'conjugationDrill', prompt: 'учиться → я ...', answer: 'учусь', explanation_uz: 'Unlidan keyin -сь: учусь.' },
      { id: 'm4-refl-2', type: 'conjugationDrill', prompt: 'учиться → он ...', answer: 'учится', explanation_uz: 'он учится.' },
      { id: 'm4-refl-3', type: 'conjugationDrill', prompt: 'заниматься → мы ...', answer: 'занимаемся', explanation_uz: 'занимаемся.' },
      { id: 'm4-refl-4', type: 'choose', prompt: "«Universitetda o'qiyman» — qaysi fe'l?", answer: 'учусь', choices: ['учусь', 'учу', 'учить', 'учил'], explanation_uz: "O'quv yurtida o'qish — учиться." },
      { id: 'm4-refl-5', type: 'fillBlank', prompt: 'Как называ___ этот фильм?', answer: 'ется', explanation_uz: 'называется.' },
      { id: 'm4-refl-6', type: 'errorHunt', prompt: 'Xatoni toping: «Я учу в школе» (o‘quvchiman ma’nosida)', answer: 'Я учусь в школе', explanation_uz: 'учиться kerak.' },
      { id: 'm4-refl-7', type: 'translate', prompt: 'Tarjima qiling: «Vokzal qayerda joylashgan?»', answer: 'Где находится вокзал?', explanation_uz: 'находиться — joylashmoq.' },
      { id: 'm4-refl-8', type: 'fillBlank', prompt: 'Дети бо___ темноты. (qo‘rqmoq)', answer: 'ятся', explanation_uz: 'боятся + Р.п.' },
    ],
  },
  {
    id: 'm4-imperative',
    module: 4,
    order: 8,
    level: 'A2',
    title: 'Buyruq mayli',
    subtitle: 'Читай! Скажите! Не забудь!',
    theory: [
      {
        heading: 'Yasalishi',
        body: "они shaklidan -ют/-ят olib tashlab: unli qolsa +й (читают → читай), undosh qolsa +и (говорят → говори). вы uchun -те qo'shiladi: читайте, говорите.",
        table: [
          ['Infinitiv', 'ты', 'вы'],
          ['чита́ть', 'чита́й', 'чита́йте'],
          ['говори́ть', 'говори́', 'говори́те'],
          ['слу́шать', 'слу́шай', 'слу́шайте'],
          ['писа́ть', 'пиши́', 'пиши́те'],
          ['сказа́ть', 'скажи́', 'скажи́те'],
        ],
      },
      {
        heading: 'Aspekt buyruqda',
        body: "Iltimos/buyruq (bajarilsin) → СВ: Скажите, пожалуйста! Прочитай это! Taqiq (qilma!) → НСВ: Не говори! Не читай! Umumiy taklif → НСВ: Заходите! (Kiring!)",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha 'qil!/qiling!' ga mos: ты → -й/-и (qil), вы → -йте/-ите (qiling). Taqiqda НСВ ishlatilishi yangi qoida: 'Не опаздывай!' (Kechikma!).",
    examples: [
      { ru: 'Скажи́те, пожа́луйста, где метро́?', uz: 'Ayting, iltimos, metro qayerda?' },
      { ru: 'Слу́шай внима́тельно!', uz: 'Diqqat bilan eshit!' },
      { ru: 'Не забу́дь ключи́!', uz: 'Kalitlarni unutma!' },
      { ru: 'Заходи́те, пожа́луйста!', uz: 'Kiring, iltimos!' },
      { ru: 'Дава́й пойдём в кино́!', uz: 'Kel, kinoga boraylik!', note: 'давай + kelasi/infinitiv' },
    ],
    commonMistakes: [
      { wrong: 'Говорите мне (bir do‘stga)', right: 'Скажи мне', why_uz: "Bir tanish odamga ты shakli: скажи." },
      { wrong: 'Не скажи никому', right: 'Не говори никому', why_uz: 'Taqiq → НСВ: не говори.' },
      { wrong: 'Читать это!', right: 'Читай это! / Прочитай это!', why_uz: 'Buyruqda maxsus shakl kerak, infinitiv emas.' },
    ],
    exercises: [
      { id: 'm4-imp-1', type: 'transform', prompt: 'Buyruq shakliga (ты): читать', answer: 'читай', explanation_uz: 'читают → чита + й.' },
      { id: 'm4-imp-2', type: 'transform', prompt: 'Buyruq shakliga (вы): говорить', answer: 'говорите', explanation_uz: 'говори + те.' },
      { id: 'm4-imp-3', type: 'transform', prompt: 'Buyruq shakliga (ты): писать', answer: 'пиши', explanation_uz: 'пишут → пиш + и.' },
      { id: 'm4-imp-4', type: 'choose', prompt: '«Kechikma!» qanday aytiladi?', answer: 'Не опаздывай!', choices: ['Не опаздывай!', 'Не опоздай!', 'Не опоздать!', 'Не опаздываешь!'], explanation_uz: 'Taqiq → НСВ buyruq.' },
      { id: 'm4-imp-5', type: 'fillBlank', prompt: '___ , пожалуйста, где банк? (сказать, вы)', answer: 'Скажите', explanation_uz: 'Iltimos → СВ: Скажите.' },
      { id: 'm4-imp-6', type: 'translate', prompt: 'Tarjima qiling: «Eshiting, iltimos!» (слушать)', answer: 'Слушайте, пожалуйста!', explanation_uz: 'слушайте.' },
      { id: 'm4-imp-7', type: 'errorHunt', prompt: 'Xatoni toping: «Не покупай! → Не купи!» qaysi to‘g‘ri taqiq?', answer: 'Не покупай!', explanation_uz: 'Taqiqda НСВ: не покупай.' },
      { id: 'm4-imp-8', type: 'translate', prompt: 'Tarjima qiling: «Kel, choy ichaylik!» (давать, пить, чай)', answer: 'Давай выпьем чай!', explanation_uz: 'Давай + СВ kelasi: выпьем.' },
    ],
    miniDialogue: [
      { speaker: 'A', ru: 'Извините, скажите, пожалуйста, где аптека?', uz: 'Kechirasiz, ayting, iltimos, dorixona qayerda?' },
      { speaker: 'B', ru: 'Идите прямо, потом поверните направо.', uz: 'To‘g‘riga yuring, keyin o‘ngga buriling.' },
      { speaker: 'A', ru: 'Спасибо большое!', uz: 'Katta rahmat!' },
      { speaker: 'B', ru: 'Пожалуйста! Не за что.', uz: 'Marhamat! Arzimaydi.' },
    ],
  },
];
