import type { GrammarTopic } from '../../types';

/** Modul 3 — Kelishiklar I: 6 kelishik, har biri alohida chuqur mavzu (A1-A2) */
export const MODULE_3: GrammarTopic[] = [
  {
    id: 'm3-cases-intro',
    module: 3,
    order: 1,
    level: 'A1',
    title: 'Kelishik tizimiga kirish',
    subtitle: '6 kelishik nima uchun kerak',
    theory: [
      {
        heading: 'Kelishik nima',
        body: "Rus tilida ot gapdagi vazifasiga qarab oxirini o'zgartiradi. 6 kelishik bor. Har biri o'z savoliga ega — savolni bilsangiz, kelishikni topasiz.",
        table: [
          ['Kelishik', 'Savollar', "O'zbek muqobili", 'Misol'],
          ['Имени́тельный (И.п)', 'кто? что?', 'bosh kelishik', 'Это кни́га'],
          ['Роди́тельный (Р.п)', 'кого? чего?', 'qaratqich (-ning)', 'нет кни́ги'],
          ['Да́тельный (Д.п)', 'кому? чему?', "jo'nalish (-ga)", 'даю́ бра́ту'],
          ['Вини́тельный (В.п)', 'кого? что?', 'tushum (-ni)', 'чита́ю кни́гу'],
          ['Твори́тельный (Т.п)', 'кем? чем?', 'bilan / vosita', 'пишу́ ру́чкой'],
          ['Предло́жный (П.п)', 'о ком? о чём? где?', "o'rin (-da, haqida)", 'в кни́ге'],
        ],
      },
      {
        heading: "Qanday o'rganamiz",
        body: "Har kelishikni alohida mavzuda, eng ko'p ishlatiladigan vaziyatlari bilan o'rganamiz. Tartib amaliy chastota bo'yicha: П.п (qayerda) → В.п (nimani) → Р.п (yo'q/kimning) → Д.п (kimga) → Т.п (nima bilan).",
      },
    ],
    comparisonWithUzbek:
      "Yaxshi yangilik: o'zbek tilida ham 6 kelishik bor! Bosh=И.п, qaratqich(-ning)=Р.п, jo'nalish(-ga)=Д.п, tushum(-ni)=В.п, o'rin(-da)=П.п, chiqish(-dan)=Р.п (из/от bilan). Farq: rus tilida qo'shimcha rod va songa qarab o'zgaradi hamda ko'pincha predlog bilan keladi.",
    examples: [
      { ru: 'Кни́га на столе́.', uz: 'Kitob stolDA.', note: 'П.п = -da' },
      { ru: 'Я чита́ю кни́гу.', uz: 'Men kitobNI o‘qiyapman.', note: 'В.п = -ni' },
      { ru: 'У меня́ нет кни́ги.', uz: 'Menda kitob yo‘q.', note: 'Р.п' },
      { ru: 'Я даю́ кни́гу дру́гу.', uz: 'Kitobni do‘stimGA beryapman.', note: 'Д.п = -ga' },
      { ru: 'Я пишу́ ру́чкой.', uz: 'Ruchka BILAN yozyapman.', note: 'Т.п' },
    ],
    commonMistakes: [
      { wrong: 'Hammasi birdan yodlashga urinish', right: 'Bitta kelishik — bitta hafta', why_uz: 'Kelishiklarni vaziyat bilan bog‘lab birin-ketin o‘rganish samaraliroq.' },
      { wrong: 'Я читаю книга', right: 'Я читаю книгу', why_uz: "To'g'ridan-to'g'ri obyekt В.п da: -а → -у." },
    ],
    exercises: [
      { id: 'm3-intro-1', type: 'choose', prompt: 'Rus tilida nechta kelishik bor?', answer: '6', choices: ['6', '4', '5', '7'], explanation_uz: '6 kelishik.' },
      { id: 'm3-intro-2', type: 'caseDetector', prompt: '«Книга на столе́» — столе qaysi kelishikda?', answer: 'Предложный', choices: ['Предложный', 'Именительный', 'Винительный', 'Дательный'], explanation_uz: "Joy (qayerda?) — П.п." },
      { id: 'm3-intro-3', type: 'caseDetector', prompt: '«Я читаю кни́гу» — книгу qaysi kelishikda?', answer: 'Винительный', choices: ['Винительный', 'Родительный', 'Дательный', 'Творительный'], explanation_uz: 'Nimani o‘qiyapman? — В.п.' },
      { id: 'm3-intro-4', type: 'choose', prompt: "O'zbekcha '-ga' qaysi kelishikka mos?", answer: 'Дательный', choices: ['Дательный', 'Родительный', 'Творительный', 'Предложный'], explanation_uz: 'Кому? — kimGA? — Д.п.' },
      { id: 'm3-intro-5', type: 'choose', prompt: "O'zbekcha '-da' qaysi kelishikka mos?", answer: 'Предложный', choices: ['Предложный', 'Винительный', 'Дательный', 'Именительный'], explanation_uz: 'Где? — qayerDA? — П.п (в/на bilan).' },
      { id: 'm3-intro-6', type: 'caseDetector', prompt: '«Я пишу ру́чкой» — ручкой qaysi kelishikda?', answer: 'Творительный', choices: ['Творительный', 'Дательный', 'Предложный', 'Родительный'], explanation_uz: 'Чем? — nima bilan? — Т.п.' },
      { id: 'm3-intro-7', type: 'choose', prompt: '«нет» so‘zidan keyin qaysi kelishik keladi?', answer: 'Родительный', choices: ['Родительный', 'Винительный', 'Дательный', 'Именительный'], explanation_uz: 'нет + Р.п: нет времени, нет денег.' },
      { id: 'm3-intro-8', type: 'caseDetector', prompt: '«Это моя кни́га» — книга qaysi kelishikda?', answer: 'Именительный', choices: ['Именительный', 'Винительный', 'Родительный', 'Предложный'], explanation_uz: 'Ega/bosh shakl — И.п.' },
    ],
  },
  {
    id: 'm3-prepositional',
    module: 3,
    order: 2,
    level: 'A1',
    title: 'Предложный: joy va mavzu',
    subtitle: 'в школе, на работе, о маме',
    theory: [
      {
        heading: 'Qachon ishlatiladi',
        body: "Предложный падеж doim predlog bilan keladi: 1) joy — в (ichida) / на (ustida, tadbirda): в школе, на столе, на работе; 2) mavzu — о (haqida): о маме, о России. Asosiy qo'shimcha: -е.",
        table: [
          ['Bosh shakl', 'П.п', 'Misol'],
          ['шко́ла', 'в шко́ле', 'maktabda'],
          ['стол', 'на столе́', 'stol ustida'],
          ['Москва́', 'в Москве́', 'Moskvada'],
          ['мо́ре', 'на мо́ре', 'dengizda'],
          ['Росси́я', 'в Росси́и', '-ия → -ии'],
          ['санато́рий', 'в санато́рии', '-ий → -ии'],
        ],
      },
      {
        heading: 'в yoki на?',
        body: "в — ichida (yopiq joy): в доме, в школе, в городе. на — yuzada yoki tadbir/ochiq joy: на столе, на улице, на работе, на уроке, на почте, на вокзале. на bilan keladigan so'zlarni yodlang: работа, урок, почта, вокзал, завод, стадион, концерт, улица.",
      },
      {
        heading: 'Istisno: -у bilan',
        body: "Ba'zi qisqa so'zlar в/на bilan -у oladi: в лесу́ (o'rmonda), в саду́ (bog'da), на полу́ (polda), в году́ (yilda), на мосту́ (ko'prikda).",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha '-da' ga teng: maktabDA = в школе. Farq: rus tilida predlog (в/на) + oxiri -е birga ishlaydi. 'Haqida' ma'nosi ham shu kelishik: kitob haqida = о книге.",
    examples: [
      { ru: 'Я живу́ в Ташке́нте.', uz: 'Men Toshkentda yashayman.' },
      { ru: 'Кни́га на столе́.', uz: 'Kitob stol ustida.' },
      { ru: 'Па́па на рабо́те.', uz: 'Dadam ishda.', note: 'работа doim на bilan' },
      { ru: 'Мы говори́м о фи́льме.', uz: 'Biz film haqida gaplashyapmiz.' },
      { ru: 'Она́ у́чится в университе́те.', uz: 'U universitetda o‘qiydi.' },
      { ru: 'Де́ти гуля́ют в саду́.', uz: 'Bolalar bog‘da sayr qilyapti.', note: 'istisno: -у' },
    ],
    commonMistakes: [
      { wrong: 'в работе', right: 'на работе', why_uz: "работа 'на' guruhidan: на работе, на работу." },
      { wrong: 'в Москва', right: 'в Москве', why_uz: 'Joy bildirilganda П.п: -а → -е.' },
      { wrong: 'о Россие', right: 'о России', why_uz: '-ия bilan tugagan otlar П.п da -ии: Россия → о России.' },
      { wrong: 'в лесе', right: 'в лесу', why_uz: 'лес istisno: в лесу́.' },
    ],
    exercises: [
      { id: 'm3-pp-1', type: 'fillBlank', prompt: 'Я живу в Ташкент___.', answer: 'е', explanation_uz: 'в Ташкенте — П.п.' },
      { id: 'm3-pp-2', type: 'fillBlank', prompt: 'Мама ___ работе. (predlog)', answer: 'на', explanation_uz: 'работа → на работе.' },
      { id: 'm3-pp-3', type: 'transform', prompt: 'П.п ga qo‘ying: школа (в ...)', answer: 'школе', explanation_uz: 'в школе.' },
      { id: 'm3-pp-4', type: 'transform', prompt: 'П.п ga qo‘ying: Россия (в ...)', answer: 'России', explanation_uz: '-ия → -ии.' },
      { id: 'm3-pp-5', type: 'choose', prompt: 'Qaysi predlog: «___ столе» (stol ustida)?', answer: 'на', choices: ['на', 'в', 'о', 'у'], explanation_uz: 'Yuzada — на.' },
      { id: 'm3-pp-6', type: 'fillBlank', prompt: 'Мы говорим ___ маме. (haqida)', answer: 'о', explanation_uz: 'о + П.п = haqida.' },
      { id: 'm3-pp-7', type: 'transform', prompt: 'П.п ga qo‘ying: лес (в ...)', answer: 'лесу', explanation_uz: 'Istisno: в лесу́.' },
      { id: 'm3-pp-8', type: 'errorHunt', prompt: 'Xatoni toping: «Брат учится в университет»', answer: 'Брат учится в университете', explanation_uz: 'Joy — П.п: в университете.' },
      { id: 'm3-pp-9', type: 'translate', prompt: 'Tarjima qiling: «Kitob sumkada» (книга, сумка)', answer: 'Книга в сумке', explanation_uz: 'в сумке — ichida.' },
      { id: 'm3-pp-10', type: 'choose', prompt: "Qaysi so'z «на» bilan keladi?", answer: 'урок', choices: ['урок', 'дом', 'школа', 'город'], explanation_uz: 'на уроке — darsda.' },
    ],
  },
  {
    id: 'm3-accusative',
    module: 3,
    order: 3,
    level: 'A1',
    title: "Винительный: to'g'ri obyekt",
    subtitle: 'читаю книгу, вижу брата',
    theory: [
      {
        heading: 'Qachon ishlatiladi',
        body: "Ish-harakat to'g'ridan-to'g'ri o'tadigan narsa (nimani? kimni?): читать книгу, смотреть фильм, любить маму. Shuningdek yo'nalish (куда?): в школу, на работу.",
        table: [
          ['Rod', "O'zgarish", 'Misol'],
          ['ж (-а/-я)', '-у/-ю', 'книга → книгу, неделя → неделю'],
          ['м jonsiz', "o'zgarmaydi", 'вижу стол'],
          ['м jonli', 'Р.п kabi: -а/-я', 'вижу брата'],
          ['с', "o'zgarmaydi", 'вижу окно'],
          ["ko'plik jonsiz", "o'zgarmaydi", 'вижу столы'],
        ],
      },
      {
        heading: "Yo'nalish: куда?",
        body: "идти/ехать + в/на + В.п = qayerGA: иду в школу, еду на работу. Solishtiring: Я в школе (qayerda? П.п) — Я иду в школу (qayerga? В.п).",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha '-ni' ga teng: kitobNI o'qiyapman = читаю книгу. Yana '-ga' (yo'nalish) ham shu kelishik bilan: maktabGA boryapman = иду в школу. Bitta ruscha kelishik o'zbekcha ikkita qo'shimchani qoplaydi.",
    examples: [
      { ru: 'Я чита́ю кни́гу.', uz: 'Men kitobni o‘qiyapman.' },
      { ru: 'Он смо́трит фильм.', uz: 'U film ko‘ryapti.', note: "м jonsiz — o'zgarmadi" },
      { ru: 'Я люблю́ ма́му.', uz: 'Men onamni yaxshi ko‘raman.' },
      { ru: 'Мы ви́дим бра́та.', uz: 'Biz akani ko‘ryapmiz.', note: 'jonli м → -а' },
      { ru: 'Я иду́ в шко́лу.', uz: 'Men maktabga ketyapman.', note: "yo'nalish" },
      { ru: 'Он е́дет на рабо́ту.', uz: 'U ishga ketyapti.' },
    ],
    commonMistakes: [
      { wrong: 'читаю книга', right: 'читаю книгу', why_uz: 'ж rod В.п da -у oladi.' },
      { wrong: 'Я иду в школе', right: 'Я иду в школу', why_uz: "Yo'nalish (qayerga?) — В.п; joy (qayerda?) — П.п." },
      { wrong: 'вижу брат', right: 'вижу брата', why_uz: 'Jonli м ot В.п da Р.п shaklini oladi.' },
      { wrong: 'люблю мама', right: 'люблю маму', why_uz: 'мама → маму.' },
    ],
    exercises: [
      { id: 'm3-acc-1', type: 'transform', prompt: 'В.п ga qo‘ying: книга (читаю ...)', answer: 'книгу', explanation_uz: '-а → -у.' },
      { id: 'm3-acc-2', type: 'transform', prompt: 'В.п ga qo‘ying: брат (вижу ...)', answer: 'брата', explanation_uz: 'Jonli м → -а.' },
      { id: 'm3-acc-3', type: 'fillBlank', prompt: 'Я люблю мам___.', answer: 'у', explanation_uz: 'маму.' },
      { id: 'm3-acc-4', type: 'choose', prompt: '«Я смотрю ...» (фильм) — qanday shakl?', answer: 'фильм (o‘zgarmaydi)', choices: ['фильм (o‘zgarmaydi)', 'фильма', 'фильму', 'фильмом'], explanation_uz: "Jonsiz м В.п da o'zgarmaydi." },
      { id: 'm3-acc-5', type: 'fillBlank', prompt: 'Я иду в школ___. (qayerga?)', answer: 'у', explanation_uz: "Yo'nalish: в школу." },
      { id: 'm3-acc-6', type: 'caseDetector', prompt: '«Я в школе» va «Я иду в школу» — ikkinchisida qaysi kelishik?', answer: 'Винительный', choices: ['Винительный', 'Предложный', 'Дательный', 'Родительный'], explanation_uz: "Куда? (yo'nalish) — В.п." },
      { id: 'm3-acc-7', type: 'errorHunt', prompt: 'Xatoni toping: «Он читает газета»', answer: 'Он читает газету', explanation_uz: 'газета → газету.' },
      { id: 'm3-acc-8', type: 'translate', prompt: 'Tarjima qiling: «Men akamni bilaman» (знать, брат)', answer: 'Я знаю брата', explanation_uz: 'Jonli м → брата.' },
      { id: 'm3-acc-9', type: 'transform', prompt: 'В.п ga qo‘ying: неделя (жду ...)', answer: 'неделю', explanation_uz: '-я → -ю.' },
      { id: 'm3-acc-10', type: 'translate', prompt: 'Tarjima qiling: «U ishga ketyapti» (ехать, работа)', answer: 'Он едет на работу', explanation_uz: 'на работу — В.п.' },
    ],
  },
  {
    id: 'm3-genitive',
    module: 3,
    order: 4,
    level: 'A2',
    title: "Родительный: yo'qlik, egalik, sanoq",
    subtitle: 'нет времени, у меня есть, два брата',
    theory: [
      {
        heading: "Uch asosiy vazifa",
        body: "1) Yo'qlik: нет + Р.п (нет времени — vaqt yo'q). 2) Egalik/mansublik: книга брата (akamning kitobi), у меня есть... 3) Sanoq: 2-4 dan keyin Р.п birlik, 5+ dan keyin Р.п ko'plik.",
        table: [
          ['Rod', 'Р.п birlik', 'Misol'],
          ['м', '-а/-я', 'стол → стола, брат → брата'],
          ['ж', '-ы/-и', 'книга → книги, неделя → недели'],
          ['с', '-а/-я', 'окно → окна, море → моря'],
        ],
      },
      {
        heading: 'Sanoq qoidasi',
        body: "1 — И.п (один стол), 2-4 — Р.п birlik (два стола), 5-20 — Р.п ko'plik (пять столов). Bu qoida 22, 23... uchun ham: двадцать два стола.",
        table: [
          ['Son', 'Shakl', 'Misol'],
          ['1, 21, 31...', 'И.п birlik', 'один год'],
          ['2-4, 22-24...', 'Р.п birlik', 'два го́да'],
          ['5-20, 25-30...', "Р.п ko'plik", 'пять лет'],
        ],
      },
      {
        heading: 'У меня есть...',
        body: "Rus tilida 'menda bor' qolipi: У + Р.п + есть + И.п: У меня есть брат. Inkori: У меня нет брата (нет + Р.п!). Olmoshlar: у меня, у тебя, у него, у неё, у нас, у вас, у них.",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha '-ning' va 'yo'q' konstruksiyalariga mos: 'akamNING kitobi' = книга брата (tartib teskari!), 'vaqt YO'Q' = нет времени. 'Menda ... bor' = У меня есть — bu ham o'zbekchaga juda yaqin.",
    examples: [
      { ru: 'У меня́ есть брат.', uz: 'Mening akam bor.' },
      { ru: 'У меня́ нет вре́мени.', uz: 'Vaqtim yo‘q.', note: 'нет + Р.п' },
      { ru: 'Э́то кни́га бра́та.', uz: 'Bu akamning kitobi.', note: 'tartib: narsa + egasi' },
      { ru: 'два сто́ла, пять столо́в', uz: 'ikkita stol, beshta stol', note: 'sanoq qoidasi' },
      { ru: 'Мне два́дцать два го́да.', uz: 'Men 22 yoshdaman.', note: '2 → года' },
      { ru: 'стака́н воды́', uz: 'bir stakan suv', note: "miqdor + Р.п" },
    ],
    commonMistakes: [
      { wrong: 'нет время', right: 'нет времени', why_uz: 'нет dan keyin doim Р.п: время → времени.' },
      { wrong: 'два столов', right: 'два стола', why_uz: '2-4 dan keyin Р.п BIRLIK: два стола.' },
      { wrong: 'пять стола', right: 'пять столов', why_uz: "5+ dan keyin Р.п KO'PLIK: пять столов." },
      { wrong: 'У меня есть нет брата', right: 'У меня нет брата', why_uz: "Inkorda 'есть' tushib qoladi." },
    ],
    exercises: [
      { id: 'm3-gen-1', type: 'fillBlank', prompt: 'У меня нет врем___. (время)', answer: 'ени', explanation_uz: 'время → времени (Р.п).' },
      { id: 'm3-gen-2', type: 'fillBlank', prompt: 'два стол___', answer: 'а', explanation_uz: '2-4 → Р.п birlik: стола.' },
      { id: 'm3-gen-3', type: 'fillBlank', prompt: 'пять стол___', answer: 'ов', explanation_uz: "5+ → Р.п ko'plik: столов." },
      { id: 'm3-gen-4', type: 'transform', prompt: 'Р.п ga qo‘ying: книга (нет ...)', answer: 'книги', explanation_uz: '-а → -и.' },
      { id: 'm3-gen-5', type: 'translate', prompt: 'Tarjima qiling: «Mening singlim bor» (сестра)', answer: 'У меня есть сестра', explanation_uz: 'У меня есть + И.п.' },
      { id: 'm3-gen-6', type: 'translate', prompt: 'Tarjima qiling: «Akam yo‘q» (брат)', answer: 'У меня нет брата', explanation_uz: 'нет + Р.п: брата.' },
      { id: 'm3-gen-7', type: 'choose', prompt: '«bu akamning mashinasi» qanday?', answer: 'это машина брата', choices: ['это машина брата', 'это брата машина', 'это машина брат', 'это брату машина'], explanation_uz: 'Egalik: narsa + egasi (Р.п).' },
      { id: 'm3-gen-8', type: 'fillBlank', prompt: 'Мне двадцать два год___.', answer: 'а', explanation_uz: '22 → oxiri 2 → года.' },
      { id: 'm3-gen-9', type: 'fillBlank', prompt: 'Мне тридцать лет. — «лет» qaysi so‘zning shakli? (год/лето)', answer: 'год', explanation_uz: "5+ bilan год o'rniga лет ishlatiladi." },
      { id: 'm3-gen-10', type: 'errorHunt', prompt: 'Xatoni toping: «У меня нет деньги»', answer: 'У меня нет денег', explanation_uz: 'деньги → денег (Р.п).' },
      { id: 'm3-gen-11', type: 'translate', prompt: 'Tarjima qiling: «bir stakan choy» (стакан, чай)', answer: 'стакан чая', explanation_uz: 'Miqdor + Р.п: чая.' },
    ],
  },
  {
    id: 'm3-dative',
    module: 3,
    order: 5,
    level: 'A2',
    title: 'Дательный: kimga, yosh, нравится',
    subtitle: 'даю брату, мне нравится, мне 20 лет',
    theory: [
      {
        heading: 'Qachon ishlatiladi',
        body: "1) Kimga berish/aytish/yordam: даю брату, звоню маме, помогаю другу. 2) Yosh: Мне 20 лет. 3) Yoqish: Мне нравится музыка. 4) Holat: Мне холодно (menga sovuq). 5) надо/нужно/можно bilan: Мне надо идти.",
        table: [
          ['Rod', 'Д.п', 'Misol'],
          ['м', '-у/-ю', 'брат → брату, учитель → учителю'],
          ['ж', '-е (-ии)', 'мама → маме, Мария → Марии'],
          ['с', '-у/-ю', 'окно → окну'],
        ],
      },
      {
        heading: 'Olmoshlar Д.п da',
        body: 'я→мне, ты→тебе, он→ему, она→ей, мы→нам, вы→вам, они→им. Bular juda ko‘p ishlatiladi: Мне нравится. Тебе помочь? Ему 30 лет.',
      },
      {
        heading: 'нравится qolipi',
        body: "O'zbekcha 'menga yoqadi' bilan bir xil qurilgan: МНЕ (kimga — Д.п) нравится КНИГА (nima — И.п). Yoqayotgan narsa ko'plikda bo'lsa: нравятся: Мне нравятся эти песни.",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha '-ga' bilan deyarli bir xil: akamGA beryapman = даю брату, menGA yoqadi = мне нравится, menGA sovuq = мне холодно. Yosh aytish ham: 'menga 20 yosh' deyish mumkin — Мне 20 лет.",
    examples: [
      { ru: 'Я даю́ кни́гу бра́ту.', uz: 'Kitobni akamga beryapman.' },
      { ru: 'Мне нра́вится э́та пе́сня.', uz: 'Menga bu qo‘shiq yoqadi.' },
      { ru: 'Мне два́дцать лет.', uz: 'Men yigirma yoshdaman.' },
      { ru: 'Я звоню́ ма́ме.', uz: 'Onamga qo‘ng‘iroq qilyapman.' },
      { ru: 'Помоги́ мне, пожа́луйста.', uz: 'Iltimos, menga yordam ber.' },
      { ru: 'Ему́ хо́лодно.', uz: 'Unga sovuq.' },
    ],
    commonMistakes: [
      { wrong: 'Я нравлюсь музыка', right: 'Мне нравится музыка', why_uz: "Yoqtiruvchi odam Д.п da (мне), yoqadigan narsa И.п da." },
      { wrong: 'Я имею 20 лет', right: 'Мне 20 лет', why_uz: "Yosh faqat Д.п bilan aytiladi." },
      { wrong: 'звоню мама', right: 'звоню маме', why_uz: "звонить + Д.п: kimGA qo'ng'iroq." },
      { wrong: 'помогаю брата', right: 'помогаю брату', why_uz: 'помогать + Д.п (В.п emas!).' },
    ],
    exercises: [
      { id: 'm3-dat-1', type: 'transform', prompt: 'Д.п ga qo‘ying: брат (даю ...)', answer: 'брату', explanation_uz: 'м → -у.' },
      { id: 'm3-dat-2', type: 'transform', prompt: 'Д.п ga qo‘ying: мама (звоню ...)', answer: 'маме', explanation_uz: 'ж → -е.' },
      { id: 'm3-dat-3', type: 'fillBlank', prompt: '___ нравится этот фильм. (men)', answer: 'Мне', explanation_uz: 'я → мне.' },
      { id: 'm3-dat-4', type: 'translate', prompt: 'Tarjima qiling: «Men 25 yoshdaman»', answer: 'Мне двадцать пять лет', explanation_uz: 'Yosh: Д.п + son + лет.' },
      { id: 'm3-dat-5', type: 'choose', prompt: 'она → Д.п?', answer: 'ей', choices: ['ей', 'её', 'ему', 'ней'], explanation_uz: 'она → ей.' },
      { id: 'm3-dat-6', type: 'errorHunt', prompt: 'Xatoni toping: «Я помогаю сестра»', answer: 'Я помогаю сестре', explanation_uz: 'помогать + Д.п: сестре.' },
      { id: 'm3-dat-7', type: 'fillBlank', prompt: 'Мне нрав___ эти песни. (yoqadi)', answer: 'ятся', explanation_uz: "Ko'plik narsa → нравятся." },
      { id: 'm3-dat-8', type: 'translate', prompt: 'Tarjima qiling: «Unga (erkak) 30 yosh»', answer: 'Ему тридцать лет', explanation_uz: 'он → ему.' },
      { id: 'm3-dat-9', type: 'fillBlank', prompt: '___ надо идти. (men)', answer: 'Мне', explanation_uz: 'надо bilan Д.п: Мне надо.' },
      { id: 'm3-dat-10', type: 'caseDetector', prompt: '«Я пишу письмо другу» — другу qaysi kelishikda?', answer: 'Дательный', choices: ['Дательный', 'Винительный', 'Родительный', 'Творительный'], explanation_uz: 'Kimga yozyapman? — Д.п.' },
    ],
  },
  {
    id: 'm3-instrumental',
    module: 3,
    order: 6,
    level: 'A2',
    title: 'Творительный: bilan, kasb, vosita',
    subtitle: 'с другом, работаю врачом, пишу ручкой',
    theory: [
      {
        heading: 'Qachon ishlatiladi',
        body: "1) Birgalik: с + Т.п (с другом — do'st bilan). 2) Vosita (predlogsiz!): пишу ручкой (ruchka bilan yozaman). 3) Kasb: работать/быть/стать + Т.п: работаю врачом. 4) Ba'zi fe'llar bilan: заниматься спортом, интересоваться музыкой.",
        table: [
          ['Rod', 'Т.п', 'Misol'],
          ['м', '-ом/-ем', 'брат → братом, учитель → учителем'],
          ['ж', '-ой/-ей', 'мама → мамой, неделя → неделей'],
          ['с', '-ом/-ем', 'окно → окном, море → морем'],
        ],
      },
      {
        heading: 'Olmoshlar Т.п da',
        body: 'я→мной, ты→тобой, он→им, она→ей, мы→нами, вы→вами, они→ими. со мной — men bilan (с → со).',
      },
      {
        heading: 'Diqqat: vosita predlogsiz',
        body: "O'zbekcha 'bilan' ikki xil tarjima qilinadi: odam bilan = с + Т.п (с братом), lekin asbob-vosita bilan = predlogsiz Т.п (пишу ручкой, режу ножом). 'с ручкой' deyish — 'ruchkani olib yurgan holda' degani!",
      },
    ],
    comparisonWithUzbek:
      "O'zbekcha 'bilan'ga mos, lekin muhim farq bor: vosita (ruchka, pichoq) predlogsiz qo'llanadi. Kasb aytish ham shu kelishikda: 'shifokor bo'lib ishlayman' = работаю врачом.",
    examples: [
      { ru: 'Я иду́ в кино́ с дру́гом.', uz: 'Do‘stim bilan kinoga boryapman.' },
      { ru: 'Я пишу́ ру́чкой.', uz: 'Ruchka bilan yozyapman.', note: 'predlogsiz!' },
      { ru: 'Он рабо́тает врачо́м.', uz: 'U shifokor bo‘lib ishlaydi.' },
      { ru: 'Она́ ста́ла учи́телем.', uz: 'U o‘qituvchi bo‘ldi.' },
      { ru: 'Я занима́юсь спо́ртом.', uz: 'Men sport bilan shug‘ullanaman.' },
      { ru: 'Пойдём со мной!', uz: 'Men bilan yur!' },
    ],
    commonMistakes: [
      { wrong: 'пишу с ручкой', right: 'пишу ручкой', why_uz: "Vosita predlogsiz Т.п da. 'с' faqat birgalik uchun." },
      { wrong: 'работаю врач', right: 'работаю врачом', why_uz: 'работать + kasb Т.п da.' },
      { wrong: 'с моя мама', right: 'с моей мамой', why_uz: 'с dan keyin Т.п: с мамой.' },
      { wrong: 'занимаюсь спорт', right: 'занимаюсь спортом', why_uz: 'заниматься + Т.п.' },
    ],
    exercises: [
      { id: 'm3-ins-1', type: 'transform', prompt: 'Т.п ga qo‘ying: друг (иду с ...)', answer: 'другом', explanation_uz: 'м → -ом.' },
      { id: 'm3-ins-2', type: 'transform', prompt: 'Т.п ga qo‘ying: мама (говорю с ...)', answer: 'мамой', explanation_uz: 'ж → -ой.' },
      { id: 'm3-ins-3', type: 'fillBlank', prompt: 'Я пишу ручк___. (vosita)', answer: 'ой', explanation_uz: 'Predlogsiz: ручкой.' },
      { id: 'm3-ins-4', type: 'fillBlank', prompt: 'Он работает врач___.', answer: 'ом', explanation_uz: 'Kasb: врачом.' },
      { id: 'm3-ins-5', type: 'choose', prompt: '«men bilan» ruscha qanday?', answer: 'со мной', choices: ['со мной', 'с я', 'с меня', 'со мне'], explanation_uz: 'я → мной, с → со.' },
      { id: 'm3-ins-6', type: 'errorHunt', prompt: 'Xatoni toping: «Я режу хлеб с ножом»', answer: 'Я режу хлеб ножом', explanation_uz: "Vosita predlogsiz: ножом." },
      { id: 'm3-ins-7', type: 'translate', prompt: 'Tarjima qiling: «Men sport bilan shug‘ullanaman»', answer: 'Я занимаюсь спортом', explanation_uz: 'заниматься + Т.п.' },
      { id: 'm3-ins-8', type: 'fillBlank', prompt: 'Она хочет стать учител___.', answer: 'ем', explanation_uz: 'стать + Т.п: учителем.' },
      { id: 'm3-ins-9', type: 'caseDetector', prompt: '«Мы едем с братом» — братом qaysi kelishikda?', answer: 'Творительный', choices: ['Творительный', 'Дательный', 'Родительный', 'Предложный'], explanation_uz: 'с + Т.п — birgalik.' },
      { id: 'm3-ins-10', type: 'translate', prompt: 'Tarjima qiling: «U onasi bilan yashaydi» (жить, мама)', answer: 'Он живёт с мамой', explanation_uz: 'с мамой.' },
    ],
  },
  {
    id: 'm3-cases-review',
    module: 3,
    order: 7,
    level: 'A2',
    title: 'Kelishiklar: umumiy jadval va aralash drill',
    subtitle: 'Hammasini birlashtiramiz',
    theory: [
      {
        heading: "To'liq jadval (birlik)",
        body: "Uchta namunaviy so'z bilan barcha kelishiklar:",
        table: [
          ['Kelishik', 'стол (м)', 'кни́га (ж)', 'окно́ (с)'],
          ['И.п (кто/что)', 'стол', 'кни́га', 'окно́'],
          ['Р.п (кого/чего)', 'стола́', 'кни́ги', 'окна́'],
          ['Д.п (кому/чему)', 'столу́', 'кни́ге', 'окну́'],
          ['В.п (кого/что)', 'стол', 'кни́гу', 'окно́'],
          ['Т.п (кем/чем)', 'столо́м', 'кни́гой', 'окно́м'],
          ['П.п (о ком/о чём)', 'о столе́', 'о кни́ге', 'об окне́'],
        ],
      },
      {
        heading: 'Kelishikni qanday topish',
        body: "1) Fe'l yoki predlogga qarang (нет→Р.п, помогать→Д.п, с→Т.п, в/на joy→П.п, в/на yo'nalish→В.п). 2) Savol bering (kimga? → Д.п). 3) O'zbekcha qo'shimcha bilan tekshiring (-ning→Р.п, -ga→Д.п/В.п, -ni→В.п, -da→П.п, bilan→Т.п).",
      },
    ],
    comparisonWithUzbek:
      "Eslab qoling: -ning → Р.п, -ga (berish) → Д.п, -ga (borish) → в/на + В.п, -ni → В.п, -da → П.п, -dan → из/от + Р.п, bilan → с + Т.п (yoki predlogsiz vosita).",
    examples: [
      { ru: 'Э́то дом. Нет до́ма. Иду́ к до́му. Ви́жу дом. Дово́лен до́мом. Говорю́ о до́ме.', uz: "Bitta so'z — olti shakl", note: 'dom har kelishikda' },
      { ru: 'Я даю́ кни́гу сестры́ бра́ту.', uz: 'Singlimning kitobini akamga beryapman.', note: 'Р.п + В.п + Д.п bitta gapda' },
    ],
    commonMistakes: [
      { wrong: 'Kelishikni tasodifiy tanlash', right: "Fe'l/predlogdan aniqlash", why_uz: "Har bir fe'l o'z kelishigini 'talab qiladi' — fe'l bilan birga yodlang: помогать кому, ждать кого/чего." },
    ],
    exercises: [
      { id: 'm3-rev-1', type: 'caseDetector', prompt: '«У меня нет сестры́» — сестры qaysi kelishik?', answer: 'Родительный', choices: ['Родительный', 'Дательный', 'Винительный', 'Творительный'], explanation_uz: 'нет + Р.п.' },
      { id: 'm3-rev-2', type: 'caseDetector', prompt: '«Я звоню́ дру́гу» — другу qaysi kelishik?', answer: 'Дательный', choices: ['Дательный', 'Родительный', 'Предложный', 'Винительный'], explanation_uz: 'звонить кому — Д.п.' },
      { id: 'm3-rev-3', type: 'caseDetector', prompt: '«Мы говори́м о фи́льме» — фильме qaysi kelishik?', answer: 'Предложный', choices: ['Предложный', 'Творительный', 'Дательный', 'Родительный'], explanation_uz: 'о + П.п.' },
      { id: 'm3-rev-4', type: 'caseDetector', prompt: '«Я е́ду с бра́том» — братом qaysi kelishik?', answer: 'Творительный', choices: ['Творительный', 'Дательный', 'Винительный', 'Предложный'], explanation_uz: 'с + Т.п.' },
      { id: 'm3-rev-5', type: 'caseDetector', prompt: '«Он лю́бит му́зыку» — музыку qaysi kelishik?', answer: 'Винительный', choices: ['Винительный', 'Родительный', 'Дательный', 'Творительный'], explanation_uz: 'любить кого/что — В.п.' },
      { id: 'm3-rev-6', type: 'fillBlank', prompt: 'Я читаю книг___ в библиотек___. (-у/-е)', answer: 'у, е', explanation_uz: 'книгу (В.п), в библиотеке (П.п).' },
      { id: 'm3-rev-7', type: 'transform', prompt: 'Barcha kerakli shaklga qo‘ying: «Я даю (книга) (брат)»', answer: 'Я даю книгу брату', explanation_uz: 'nimani → книгу (В.п), kimga → брату (Д.п).' },
      { id: 'm3-rev-8', type: 'errorHunt', prompt: 'Xatoni toping: «Я живу в Ташкент с моя семья»', answer: 'Я живу в Ташкенте с моей семьёй', explanation_uz: 'в Ташкенте (П.п), с моей семьёй (Т.п).' },
      { id: 'm3-rev-9', type: 'choose', prompt: "o'zbekcha '-da' → ruscha qaysi qolip?", answer: 'в/на + П.п', choices: ['в/на + П.п', 'в/на + В.п', 'с + Т.п', 'у + Р.п'], explanation_uz: 'Joy: в школе, на работе.' },
      { id: 'm3-rev-10', type: 'translate', prompt: 'Tarjima qiling: «Onamga gul beryapman» (давать, цветы, мама)', answer: 'Я даю цветы маме', explanation_uz: 'цветы (В.п), маме (Д.п).' },
      { id: 'm3-rev-11', type: 'caseDetector', prompt: '«стака́н ча́я» — чая qaysi kelishik?', answer: 'Родительный', choices: ['Родительный', 'Винительный', 'Дательный', 'Именительный'], explanation_uz: 'Miqdor + Р.п.' },
      { id: 'm3-rev-12', type: 'transform', prompt: '«Мы е́дем на (мо́ре)» — kerakli shakl?', answer: 'море', explanation_uz: "Yo'nalish В.п: с rod o'zgarmaydi — на море." },
    ],
  },
];
